defaults: &defaults
  endpoint: <%= ENV['KEYSTORM_ENDPOINT'] || 'https://localhost:3000/' %>
  cloud: <%= ENV['KEYSTORM_CLOUD'] || 'opennebula' %>
  opennebula:
    endpoint: <%= ENV['KEYSTORM_OPENNEBULA_ENDPOINT'] || 'http://localhost:2633/RPC2' %>
    secret: <%= ENV['KEYSTORM_OPENNEBULA_SECRET'] %>
  log_level: <%= ENV['KEYSTORM_LOG_LEVEL'] || 'info' %>
  audit_file: <%= ENV['KEYSTORM_AUDIT_FILE'] || Rails.root.join('log', 'audit.log') %>
  behind_proxy: <%= ENV['KEYSTORM_BEHIND_PROXY'] || true %>
  token_cipher: <%= ENV['KEYSTORM_TOKEN_CIPHER'] || 'AES-128-CBC' %>
  token_key: <%= ENV['KEYSTORM_TOKEN_KEY'] %>
  token_iv: <%= ENV['KEYSTORM_TOKEN_IV'] %>
  memcache: <%= ENV['KEYSTORM_MEMCACHE'] || 'localhost:11211' %>
  oidc:
    matcher: <%= ENV['KEYSTORM_OIDC_MATCHER'] || 'urn:mace:egi.eu:aai.egi.eu:{role}@{group}' %>
  voms:
    default_email: <%= ENV['KEYSTORM_VOMS_DEFAULT_EMAIL'] || 'root@localhost' %>
  catalog: # List of catalog entries
    - endpoints:
        - region_id: rOCCI-server
          url: <%= ENV['KEYSTORM_CATALOG_ENDPOINTS_URL'] || 'https://localhost:11443/' %>
          region: rOCCI-server
          interface: public
          id: 8d243dbd892234d1bccfbfb29f2ad947b2ae4cd2
      type: compute
      id: 82615421269f13b16e8744d2d84509b0c0c76de5
      name: rOCCI-server

production:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults
  token_key: abcdefghijklmnop
  token_iv: zyxwvutsrqponmlk
  opennebula:
    secret: oneadmin:opennebula
